name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev cmake make libudev-dev libopenal-dev

    - name: Debug OpenAL paths
      run: |
        ls /usr/lib/x86_64-linux-gnu/libopenal.so
        ls /usr/include/AL/al.h

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DOPENAL_LIBRARY=/usr/lib/x86_64-linux-gnu/libopenal.so \
          -DOPENAL_INCLUDE_DIR=/usr/include/AL

    - name: Build project
      run: cmake --build build