name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Ensure system is ready for CMake installation
      run: |
        if (Test-Path "C:\ProgramData\chocolatey\lib\cmake.install") {
          choco uninstall cmake.install -y
        }
        if (Test-Path "C:\ProgramData\chocolatey\lib\cmake") {
          choco uninstall cmake -y
        }
        if (Test-Path "C:\Program Files\CMake") {
          Remove-Item "C:\Program Files\CMake" -Recurse -Force
        }

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build --config Release