name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SFML
      run: |
        sudo apt-get update
        sudo apt-get install libsfml-dev
    - name: Clean
      run: make clean 
    - name: Build
      run: make 
   